[package]
name = "chainx-primitives"
version = "0.1.0"
authors = ["Chainpool <http://www.chainx.org>"]

[dependencies]
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
substrate-codec = { git = "https://github.com/chainx-org/substrate", default_features = false }
substrate-codec-derive = { git = "https://github.com/chainx-org/substrate", default_features = false }
substrate-primitives = { git = "https://github.com/chainx-org/substrate", default_features = false }
substrate-runtime-std = { git = "https://github.com/chainx-org/substrate", default_features = false }
substrate-runtime-primitives = { git = "https://github.com/chainx-org/substrate", default_features = false }

[dev-dependencies]
substrate-serializer = { git = "https://github.com/chainx-org/substrate" }
pretty_assertions = "0.4"

[features]
default = ["std"]
std = [
	"substrate-codec/std",
	"substrate-primitives/std",
	"substrate-runtime-std/std",
	"substrate-runtime-primitives/std",
	"serde/std",
    "serde_derive",
]
