[package]
name = "chainx-executor"
version = "0.1.0"
authors = ["Chainpool <http://www.chainx.org>"]

[dependencies]
substrate-executor = { git = "https://github.com/paritytech/substrate" }
substrate-primitives = { git = "https://github.com/paritytech/substrate" }
chainx-runtime = { path = "../runtime" }
